version: "3"
services:
  nginx:
    image: nginx:1.13.8-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./www:/var/www/:rw
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes: 
      - ./redis/redis.conf:/etc/redis.conf:ro
      - ./redis/data:/data/:rw
    entrypoint: ["redis-server", "/etc/redis.conf"]
  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes: 
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123123